configVersion: 1.0.0
componentName: tcpip_network_config
coreVersion: 5.8.4
device: PIC32MZ1025W104132
library: []
dependency:
- dependencyPackage: class com.microchip.mcc.harmony.HarmonyModule
  name: tcpip_network_config
  type: module
  version: ''
- dependencyPackage: ''
  name: net
  type: package
  version: v3.14.5
customDataClassName: com.microchip.utils_mh3.utils.persistence.CustomModuleData
data:
  attachments: {}
  elementPosition:
    attributes:
      id: NETWORK LAYER
    children:
    - children:
      - attributes:
          id: tcpip_network_config
          x: '20'
          y: '20'
        type: ElementPosition
      type: ElementPositions
    type: ComponentGraph
  symbols: {}
  userData: {}
